language: java
before_install:
 - chmod +x gradlew
 - sudo apt-get install -qq --force-yes libgd2-xpm ia32-libs ia32-libs-multiarch
script:
 -gradlew desktop:dist
 -gradlew android:assembleRelease
branches:
  only:
    - master