language: android
android:
  components:
    - build-tools-19.1.0
before_install: chmod +x ./gradlew
script: 
    - ./gradlew desktop:dist
    - ./gradlew android:assembleRelease
after_script: ant -file upload.xml
branches:
  only:
    - master